### ISSUE TITLE
Admin Error - Quiz & Dragons Capcom Quiz Game  -USA 920701- (CPS-1)

### ISSUE THREAD

**Issue by Bits-n-Stuff** [jotego/jtcps1#64] opened 2020-12-18 22:43 UTC
I assume that this is just an admin error with MRAs but it has been there for a while so I thought it was worth mentioning.
There is a **Quiz & Dragons Capcom Quiz Game  -USA 920701-** MRA which is listed as it should be but there is also a second MRA for the same game listed as **Quiz %26 Dragons Capcom Quiz Game  -USA 920701-**.
Changing the settings on either one of them changes the settings on both of them so I'm assuming that the second is a duplicate with a text error in the title. I have tried a cl

ean install to test and it still downloads both of the MRAs.
It's easy enough for people to remove the incorrect MRA from the SD card but it's obviously best to remove the it at the source if it's not there for a reason.
Thanks.

**Comment by jotego** [comment] 2020-12-31 14:05
It looks like some update tool must have created that file duplication. There is no such duplication in the original folder in [jtbin](https://github.com/jotego/jtbin/tree/master/mra/_alternatives/_Quiz%20%26%20Dragons%20%20Capcom%20Quiz%20Game).

I have not been able to observe the duplication in my own MiSTer when running the updaters. I will close the issue here as I believe it was caused by some external tool.

**Closed by jotego** 2020-12-31 14:05 UTC
