### ISSUE TITLE
CPS1: KOD Only one credit starts the game

### ISSUE THREAD

**Issue by maxxsun** [jotego/jtcps1#115] opened 2021-10-08 13:54 UTC
jtcps1_20211002     only one credit can start the game
https://www.youtube.com/watch?v=2FEMQDh0h6s

**Comment by jotego** [comment] 2021-12-22 12:03
The problem is that if you enter more than one credit and press 1P, the credit counter will go down but the game won't start. This repeats until you have 1 credit, then the game will start.

Items tested without effect:
-DIP switch settings (tested in MAME for unused pins)
-Disabling dial_cs
-Disabling ppu2_cs via 'h1Cx
-Disabling joy_cs
-Making the CPS-B ID 16'hFFFF

**Comment by jotego** [comment] 2022-01-12 09:08
Enabling the turbo mode in the OSD fixes the problem. The CPU speed seems to be wrongly assigned to 10MHz in this game. It should be 12MHz.

**Closed** 2022-01-12 16:50 UTC

**Comment by jotego** [comment] 2022-01-12 18:46
The files are updated now in JTBIN. You will need to update both the RBD and the MRA to get the correct behaviour. Thanks for reporting this :-)
